<?php

namespace App\Console;

use App\Console\Commands\DemoCron;
use App\Models\Utility\Address\Address;
use App\Models\Utility\Script\Script;
use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Illuminate\Support\Facades\Artisan;

class Kernel extends ConsoleKernel {
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        //
        Commands\DemoCron::class
    ];

    /**
     * Define the application's command schedule.
     *
     * @param \Illuminate\Console\Scheduling\Schedule $schedule
     *
     * @return void
     */
    protected function schedule( Schedule $schedule ) {
        $scripts = Script::
        where( "active_status_id", 1200 )->
        whereIn( "run_status_id", [410100,410500] )-> /// در انتظار اجرا یا در انتظار اجرای فرمان بعدی
        whereIn( "script_type_id", [ 1, 3 ] )->
        orderBy( "priority" )->
        get();


        foreach ( $scripts as $script ) {
            $script_last_update = Script::find( $script->id );
            if ( $script_last_update->AllowRunScript() ) {
                $script_last_update->startOperation();
                Artisan::call( 'script:s' . $script_last_update->code );
                $script_last_update->endOperation();

            }
        }

    }

    public function scheduleTimezone() {
        return parent::scheduleTimezone(); // TODO: Change the autogenerated stub
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands() {
        $this->load( __DIR__ . '/Commands' );

        require base_path( 'routes/console.php' );
    }
}
