<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\Exceptions\ThrottleRequestsException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        // Create a renderable
        // see https://laravel.com/docs/10.x/errors#rendering-exceptions
        $this->renderable(function (ThrottleRequestsException $e) {

//            if (RateLimiter::tooManyAttempts('send-message:'.Auth::id(), $perMinute = 20)) {
//                $seconds = RateLimiter::availableIn('send-message:'.Auth::id());
//
//            return redirect()->route("da")
//                ->with( ["success"=>'You may try again in '.$seconds.' seconds.']);
//
//            }


        });
    }
    protected function shouldReturnJson( $request, Throwable $e ) {
        return parent::shouldReturnJson( $request, $e ); // TODO: Change the autogenerated stub
    }

}
