<?php

namespace Database\Seeders\OldSeeder;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder {
    private $data = [
        [ 'id' => 1, 'area_code' => 221, 'caption' => 'سنگال' ],
        [ 'id' => 2, 'area_code' => 46, 'caption' => 'سوئد' ],
        [ 'id' => 3, 'area_code' => 41, 'caption' => 'سوئيس' ],
        [ 'id' => 4, 'area_code' => 249, 'caption' => 'سودان' ],
        [ 'id' => 5, 'area_code' => 597, 'caption' => 'سورينام' ],
        [ 'id' => 6, 'area_code' => 963, 'caption' => 'سوريه' ],
        [ 'id' => 7, 'area_code' => 252, 'caption' => 'سومالي' ],
        [ 'id' => 8, 'area_code' => 148, 'caption' => 'سيشل' ],
        [ 'id' => 9, 'area_code' => 56, 'caption' => 'شيلي' ],
        [ 'id' => 10, 'area_code' => 381, 'caption' => 'صربستان و مونته نگرو' ],
        [ 'id' => 11, 'area_code' => 96, 'caption' => 'عربستان' ],
        [ 'id' => 12, 'area_code' => 968, 'caption' => 'عمان' ],
        [ 'id' => 13, 'area_code' => 233, 'caption' => 'غنا' ],
        [ 'id' => 14, 'area_code' => 33, 'caption' => 'فرانسه' ],
        [ 'id' => 15, 'area_code' => 358, 'caption' => 'فنلاند' ],
        [ 'id' => 16, 'area_code' => 679, 'caption' => 'فيجي' ],
        [ 'id' => 17, 'area_code' => 63, 'caption' => 'فيليپين' ],
        [ 'id' => 18, 'area_code' => 357, 'caption' => 'قبرس' ],
        [ 'id' => 19, 'area_code' => 7331, 'caption' => 'قرقيزستان' ],
        [ 'id' => 20, 'area_code' => 974, 'caption' => 'قطر' ],
        [ 'id' => 21, 'area_code' => 855, 'caption' => 'کامبوج' ],
        [ 'id' => 22, 'area_code' => 237, 'caption' => 'کامرون' ],
        [ 'id' => 23, 'area_code' => 1, 'caption' => 'کانادا' ],
        [ 'id' => 24, 'area_code' => 82, 'caption' => 'کره جنوبي' ],
        [ 'id' => 25, 'area_code' => 850, 'caption' => 'کره شمالي' ],
        [ 'id' => 26, 'area_code' => 385, 'caption' => 'کرواسي' ],
        [ 'id' => 27, 'area_code' => 506, 'caption' => 'کاستاريکا' ],
        [ 'id' => 28, 'area_code' => 57, 'caption' => 'کلمبيا' ],
        [ 'id' => 29, 'area_code' => 242, 'caption' => 'کنگو' ],
        [ 'id' => 30, 'area_code' => 254, 'caption' => 'کنيا' ],
        [ 'id' => 31, 'area_code' => 53, 'caption' => 'کوبا' ],
        [ 'id' => 32, 'area_code' => 269, 'caption' => 'کومور' ],
        [ 'id' => 33, 'area_code' => 965, 'caption' => 'کويت' ],
        [ 'id' => 34, 'area_code' => 241, 'caption' => 'گابون' ],
        [ 'id' => 35, 'area_code' => 220, 'caption' => 'گامبيا' ],
        [ 'id' => 36, 'area_code' => 955, 'caption' => 'گرجستان' ],
        [ 'id' => 37, 'area_code' => 1473, 'caption' => 'گرنادا' ],
        [ 'id' => 38, 'area_code' => 502, 'caption' => 'گواتمالا' ],
        [ 'id' => 39, 'area_code' => 671, 'caption' => 'گوام' ],
        [ 'id' => 40, 'area_code' => 224, 'caption' => 'گينه' ],
        [ 'id' => 41, 'area_code' => 240, 'caption' => 'گينه استوايي' ],
        [ 'id' => 42, 'area_code' => 245, 'caption' => 'گينه بيسائو' ],
        [ 'id' => 43, 'area_code' => 856, 'caption' => 'لائوس' ],
        [ 'id' => 44, 'area_code' => 961, 'caption' => 'لبنان' ],
        [ 'id' => 45, 'area_code' => 266, 'caption' => 'لسوتو' ],
        [ 'id' => 46, 'area_code' => 48, 'caption' => 'لهستان' ],
        [ 'id' => 47, 'area_code' => 352, 'caption' => 'لوکزامبورگ' ],
        [ 'id' => 48, 'area_code' => 231, 'caption' => 'ليبريا' ],
        [ 'id' => 49, 'area_code' => 218, 'caption' => 'ليبي' ],
        [ 'id' => 50, 'area_code' => 265, 'caption' => 'مالاوي' ],
        [ 'id' => 51, 'area_code' => 356, 'caption' => 'مالت' ],
        [ 'id' => 52, 'area_code' => 960, 'caption' => 'مالديو' ],
        [ 'id' => 53, 'area_code' => 60, 'caption' => 'مالزي' ],
        [ 'id' => 54, 'area_code' => 223, 'caption' => 'مالي' ],
        [ 'id' => 55, 'area_code' => 36, 'caption' => 'مجارستان' ],
        [ 'id' => 56, 'area_code' => 212, 'caption' => 'مراکش' ],
        [ 'id' => 57, 'area_code' => 20, 'caption' => 'مصر' ],
        [ 'id' => 58, 'area_code' => 976, 'caption' => 'مغولستان' ],
        [ 'id' => 59, 'area_code' => 389, 'caption' => 'مقدونيه' ],
        [ 'id' => 60, 'area_code' => 222, 'caption' => 'موريتاني' ],
        [ 'id' => 61, 'area_code' => 230, 'caption' => 'موريس' ],
        [ 'id' => 62, 'area_code' => 258, 'caption' => 'موزامبيک' ],
        [ 'id' => 63, 'area_code' => 95, 'caption' => 'ميانمار' ],
        [ 'id' => 64, 'area_code' => 52, 'caption' => 'مکزيک' ],
        [ 'id' => 65, 'area_code' => 674, 'caption' => 'نائورا' ],
        [ 'id' => 66, 'area_code' => 264, 'caption' => 'ناميبيا' ],
        [ 'id' => 67, 'area_code' => 977, 'caption' => 'نپال' ],
        [ 'id' => 68, 'area_code' => 47, 'caption' => 'نروژ' ],
        [ 'id' => 69, 'area_code' => 267, 'caption' => 'نگارا پرونئي دارالسلام' ],
        [ 'id' => 70, 'area_code' => 227, 'caption' => 'نيجر' ],
        [ 'id' => 71, 'area_code' => 505, 'caption' => 'نيکاراگوئه' ],
        [ 'id' => 72, 'area_code' => 509, 'caption' => 'هائي تي' ],
        [ 'id' => 73, 'area_code' => 31, 'caption' => 'هلند' ],
        [ 'id' => 74, 'area_code' => 91, 'caption' => 'هند' ],
        [ 'id' => 75, 'area_code' => 504, 'caption' => 'هندوراس' ],
        [ 'id' => 76, 'area_code' => 752, 'caption' => 'هنگ کنگ' ],
        [ 'id' => 77, 'area_code' => 39, 'caption' => 'واتيکان' ],
        [ 'id' => 78, 'area_code' => 58, 'caption' => 'ونزوئلا' ],
        [ 'id' => 79, 'area_code' => 84, 'caption' => 'ويتنام' ],
        [ 'id' => 80, 'area_code' => 969, 'caption' => 'يمن جنوبي' ],
        [ 'id' => 81, 'area_code' => 967, 'caption' => 'يمن شمالي' ],
        [ 'id' => 82, 'area_code' => 381, 'caption' => 'يوگسلاوي' ],
        [ 'id' => 83, 'area_code' => 30, 'caption' => 'يونان' ],
        [ 'id' => 84, 'area_code' => 994, 'caption' => 'آذربايجان' ],
        [ 'id' => 85, 'area_code' => 54, 'caption' => 'آرژانتين' ],
        [ 'id' => 86, 'area_code' => 27, 'caption' => 'آفريقاي جنوبي' ],
        [ 'id' => 87, 'area_code' => 236, 'caption' => 'آفريقاي مرکزي' ],
        [ 'id' => 88, 'area_code' => 355, 'caption' => 'آلباني' ],
        [ 'id' => 89, 'area_code' => 49, 'caption' => 'آلمان' ],
        [ 'id' => 90, 'area_code' => 1, 'caption' => 'آمريکا' ],
        [ 'id' => 91, 'area_code' => 244, 'caption' => 'آنگولا' ],
        [ 'id' => 92, 'area_code' => 43, 'caption' => 'اتريش' ],
        [ 'id' => 93, 'area_code' => 351, 'caption' => 'اتيوپي' ],
        [ 'id' => 94, 'area_code' => 962, 'caption' => 'اردن' ],
        [ 'id' => 95, 'area_code' => 374, 'caption' => 'ارمنستان' ],
        [ 'id' => 96, 'area_code' => 598, 'caption' => 'اروگوئه' ],
        [ 'id' => 97, 'area_code' => 291, 'caption' => 'اريتره' ],
        [ 'id' => 98, 'area_code' => 7371, 'caption' => 'ازبکستان' ],
        [ 'id' => 99, 'area_code' => 34, 'caption' => 'اسپانيا' ],
        [ 'id' => 100, 'area_code' => 61, 'caption' => 'استراليا' ],
        [ 'id' => 101, 'area_code' => 372, 'caption' => 'استوني' ],
        [ 'id' => 102, 'area_code' => 43, 'caption' => 'اطريش' ],
        [ 'id' => 103, 'area_code' => 93, 'caption' => 'افغانستان' ],
        [ 'id' => 104, 'area_code' => 213, 'caption' => 'الجزاير' ],
        [ 'id' => 105, 'area_code' => 503, 'caption' => 'السالوادور' ],
        [ 'id' => 106, 'area_code' => 971, 'caption' => 'امارات' ],
        [ 'id' => 107, 'area_code' => 62, 'caption' => 'اندونزي' ],
        [ 'id' => 108, 'area_code' => 44, 'caption' => 'انگلستان' ],
        [ 'id' => 109, 'area_code' => 25, 'caption' => 'اوگاندا' ],
        [ 'id' => 110, 'area_code' => 380, 'caption' => 'اوکراين' ],
        [ 'id' => 111, 'area_code' => 39, 'caption' => 'ايتاليا' ],
        [ 'id' => 112, 'area_code' => 98, 'caption' => 'ایران' ],
        [ 'id' => 113, 'area_code' => 353, 'caption' => 'ايرلند' ],
        [ 'id' => 114, 'area_code' => 593, 'caption' => 'اکوادور' ],
        [ 'id' => 115, 'area_code' => 354, 'caption' => 'ايسلند' ],
        [ 'id' => 116, 'area_code' => 18094, 'caption' => 'باربادوس' ],
        [ 'id' => 117, 'area_code' => 18093, 'caption' => 'باهاما' ],
        [ 'id' => 118, 'area_code' => 973, 'caption' => 'بحرين' ],
        [ 'id' => 119, 'area_code' => 55, 'caption' => 'برزيل' ],
        [ 'id' => 120, 'area_code' => 673, 'caption' => 'بروئني' ],
        [ 'id' => 121, 'area_code' => 32, 'caption' => 'بلژيک' ],
        [ 'id' => 122, 'area_code' => 359, 'caption' => 'بلغارستان' ],
        [ 'id' => 123, 'area_code' => 880, 'caption' => 'بنگلادش' ],
        [ 'id' => 124, 'area_code' => 229, 'caption' => 'بنين' ],
        [ 'id' => 125, 'area_code' => 267, 'caption' => 'بوتان' ],
        [ 'id' => 126, 'area_code' => 387, 'caption' => 'بوسني و هرزگوين' ],
        [ 'id' => 127, 'area_code' => 591, 'caption' => 'بوليوي' ],
        [ 'id' => 128, 'area_code' => 595, 'caption' => 'پاراگوئه' ],
        [ 'id' => 129, 'area_code' => 507, 'caption' => 'پاناما' ],
        [ 'id' => 130, 'area_code' => 92, 'caption' => 'پاکستان' ],
        [ 'id' => 131, 'area_code' => 351, 'caption' => 'پرتغال' ],
        [ 'id' => 132, 'area_code' => 51, 'caption' => 'پرو' ],
        [ 'id' => 133, 'area_code' => 95, 'caption' => 'پنال' ],
        [ 'id' => 134, 'area_code' => 992, 'caption' => 'تاجيکستان' ],
        [ 'id' => 135, 'area_code' => 255, 'caption' => 'تانزانيا' ],
        [ 'id' => 136, 'area_code' => 66, 'caption' => 'تايلند' ],
        [ 'id' => 137, 'area_code' => 886, 'caption' => 'تايوان' ],
        [ 'id' => 138, 'area_code' => 1868, 'caption' => 'ترينيداد' ],
        [ 'id' => 139, 'area_code' => 7363, 'caption' => 'ترکمنستان' ],
        [ 'id' => 140, 'area_code' => 90, 'caption' => 'ترکيه' ],
        [ 'id' => 141, 'area_code' => 216, 'caption' => 'تونس' ],
        [ 'id' => 142, 'area_code' => 676, 'caption' => 'تونگا' ],
        [ 'id' => 143, 'area_code' => 18099, 'caption' => 'جامائيکا' ],
        [ 'id' => 144, 'area_code' => 359, 'caption' => 'جزاير قناري' ],
        [ 'id' => 145, 'area_code' => 692, 'caption' => 'جزايرمارشال' ],
        [ 'id' => 146, 'area_code' => 237, 'caption' => 'چاد' ],
        [ 'id' => 147, 'area_code' => 86, 'caption' => 'چين' ],
        [ 'id' => 148, 'area_code' => 42, 'caption' => 'چک' ],
        [ 'id' => 149, 'area_code' => 45, 'caption' => 'دانمارک' ],
        [ 'id' => 150, 'area_code' => 508, 'caption' => 'دومينيکا' ],
        [ 'id' => 151, 'area_code' => 1809, 'caption' => 'دومينيکن' ],
        [ 'id' => 152, 'area_code' => 250, 'caption' => 'رو آندا' ],
        [ 'id' => 153, 'area_code' => 7095, 'caption' => 'روسيه' ],
        [ 'id' => 154, 'area_code' => 40, 'caption' => 'روماني' ],
        [ 'id' => 155, 'area_code' => 243, 'caption' => 'زئير' ],
        [ 'id' => 156, 'area_code' => 260, 'caption' => 'زامبيا' ],
        [ 'id' => 157, 'area_code' => 64, 'caption' => '    زلاند نو' ],
        [ 'id' => 158, 'area_code' => 263, 'caption' => 'زيمبابوه' ],
        [ 'id' => 159, 'area_code' => 81, 'caption' => 'ژاپن' ],
        [ 'id' => 160, 'area_code' => 225, 'caption' => 'ساحل عاج' ],
        [ 'id' => 161, 'area_code' => 684, 'caption' => 'ساموآ آمريکا' ],
        [ 'id' => 162, 'area_code' => 685, 'caption' => 'ساموا غربي' ],
        [ 'id' => 163, 'area_code' => 94, 'caption' => 'سريلانکا' ],
        [ 'id' => 164, 'area_code' => 1758, 'caption' => 'سنت لوسيا' ],
        [ 'id' => 165, 'area_code' => 1784, 'caption' => 'سنت وينسنت' ],
        [ 'id' => 166, 'area_code' => 1869, 'caption' => 'سنت کيتس' ],
        [ 'id' => 167, 'area_code' => 65, 'caption' => 'سنگاپور' ],
    ];
    private $table = 'countries';

    public function run() {
        DB::table( $this->table )->delete();
        foreach ( $this->data as $item ) {
            DB::table( $this->table )->insert( $item );
        }
    }
}
